platform :ios, '13.0'

target 'Native_Basic' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Native_Basic
  
    pod 'THEOplayerSDK-core', '~> 5'
    
end
