platform :ios, '13.0'

target 'Offline_Playback' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Offline_Playback

    pod 'THEOplayerSDK-core', '~> 9'

end
