platform :ios, '15.0'
source 'https://github.com/THEOplayer/cocoapods-specs.git'
source 'https://cdn.cocoapods.org'

target 'Basic_Playback' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Basic_Playback
  
    pod 'THEOplayerSDK-core', '~> 11'
    
end
