# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'Basic_Playback' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Basic_Playback
  
    pod 'THEOplayerSDK-basic'
    
end
