platform :ios, '15.0'

target 'Basic_Playback' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Basic_Playback
  
    pod 'THEOplayerSDK-core', '~> 11'
    
end
