platform :ios, '13.0'

target 'DRM_Playback' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DRM_Playback
  pod 'THEOplayerSDK-core', '~> 8'
end
