platform :ios, '13.0'

target 'Native_GoogleCast' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Native_GoogleCast
  
    pod 'THEOplayerSDK-core', '~> 8'
    pod 'THEOplayer-Integration-GoogleCast', '~> 8'
    
end
