# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'Full_Screen_Handling' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Full_Screen_Handling
  
    pod 'THEOplayerSDK-basic'
    
end
