# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'Simple_OTT' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Simple_OTT
  pod 'ReachabilitySwift'
  pod 'UICircularProgressRing'
  pod 'FontAwesome.swift'
  pod 'google-cast-sdk', '4.3.0'
  pod 'GoogleAds-IMA-iOS-SDK', '~> 3.11.4'
end
