platform :ios, '13.0'

target 'Google_Cast' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Google_Cast
  pod 'THEOplayerSDK-core', '~> 10'
  pod 'THEOplayer-Integration-GoogleCast', '~> 10'
end
